# Generated by Django 5.1.1 on 2024-09-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="display_name",
            new_name="name",
        ),
    ]
